CREATE SEQUENCE budynek_seq START WITH 1;
CREATE SEQUENCE sala_seq START WITH 1;
CREATE SEQUENCE kierunek_seq START WITH 1;
CREATE SEQUENCE przedmiot_seq START WITH 1;
CREATE SEQUENCE pracownik_seq START WITH 1;
CREATE SEQUENCE student_seq START WITH 1;